[package]
name = "vl-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
busrt = { version = "0.4.19", features = ["ipc", "rpc"] }
futures = "0.3.31"
log = "0.4.27"
rmp-serde = "1.3.0"
serde = "1.0.219"
simplelog = "0.12.2"
tokio = "1.44.2"
vl-linux-backend = { path = "../vl-linux-backend" }
