[package]
name = "vl-global"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.98"
config = "0.15.11"
homedir = "0.3.4"
indexmap = "2.9.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
toml = "0.8.22"
