[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-L",
  "/usr/lib/x86_64-linux-gnu",
  "-l",
  "espeak-ng",
  "-l",
  "sonic",
  "-l",
  "pcaudio",
]
[target.aarch64-linux-android]
linker = "/path/to/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android31-clang"
rustflags = ["-C", "link-arg=-landroid", "-C", "link-arg=-llog"]
